# Generated by Django 6.0.5 on 2026-05-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('INTERVIEW', 'Interviewing'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected')])),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('job_url', models.URLField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
